- hosts: cassandra-node
  sudo: true
  remote_user: root
  vars:
    cassandra_seeds: "{{ groups['cassandra-node'] | map('extract', hostvars, ['ansible_ssh_host']) | list }}"
    cassandra_cluster_name: TestCluster
    cassandra_listen_address: "{{ansible_ssh_host}}"
    cassandra_rpc_address: "0.0.0.0"
    opscenter_ip: "{{ groups['opscenter-node'] | map('extract', hostvars, ['ansible_ssh_host']) | list | first }}"
  tasks:
    - name: install Datastax YUM repo
      copy:
        content: |
          [datastax]
          name = DataStax Repo for Apache Cassandra
          baseurl = http://rpm.datastax.com/community
          enabled = 1
          gpgcheck = 0
        dest: /etc/yum.repos.d/datastax.repo
    - name: Yum update
      shell: /usr/bin/yum update -y
    - name: Install all require RPMs
      yum: name={{item}} state=present
      with_items:
        - vim
        - net-tools
        - java-1.8.0-openjdk
        - dsc20
        - cassandra20
        - datastax-agent

    - name: Update C* config file
      template:
        src: cassandra.yaml.j2
        dest: /etc/cassandra/conf/cassandra.yaml

    - name: Enable C*
      shell: /sbin/chkconfig cassandra on
    - name: Stop C*
      service: name=cassandra state=stopped
    - name: Clean all C* data
      shell: rm -rf /var/lib/cassandra/data/system/*
    - name: Start C*
      service: name=cassandra state=started

    - name: Configure Datastax Agent
      copy:
        content: "stomp_interface: {{opscenter_ip}}"
        dest: /var/lib/datastax-agent/conf/address.yaml
    - name: Enable Datastax Agent
      shell: /sbin/chkconfig datastax-agent on
    - name: Stop Datastax Agent
      service: name=datastax-agent state=stopped
    - name: Start Datastax Agent
      service: name=datastax-agent state=started
